language: scala
scala:
  - 2.9.3
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libboost1.48-all-dev -qq
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.7
 script: "./test.sh" 
